class Exporter {
    static toMarkdown(report) {
        let md = `# EPHEMERAL Analysis Report\n`;
        md += `Generated: ${report.timestamp}\n\n`;
        md += `## Overall Risk Score: ${report.score}/100\n\n`;
        md += `### Analyst Summary\n> ${report.summary}\n\n`;

        md += `## Anomalies Detected\n`;
        if (report.anomalies.length === 0) {
            md += `* No significant anomalies detected.\n`;
        } else {
            report.anomalies.forEach(a => {
                md += `* **[${a.level}]** ${a.msg}\n`;
            });
        }

        md += `\n## Header Authentication\n`;
        // Add more details here...

        md += `\n---\n*Report generated by Ephemeral Email Analysis Tool. No data was stored during this process.*`;
        return md;
    }

    static toJSON(report) {
        return JSON.stringify(report, null, 2);
    }

    static download(content, filename, type) {
        const blob = new Blob([content], { type: type });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }
}
